# Generated by Django 6.0.5 on 2026-06-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
