# Generated by Django 6.0.5 on 2026-06-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0005_alter_user_email_alter_user_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='temp_user', max_length=60, unique=True),
        ),
    ]
