"""""
Django settings for attendance project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gs6w^wyc@(h0xplf)(_-)u7)pcd4ps9q+p5x9k*lz)6(swpbgn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# telling django to use my custom form
AUTH_USER_MODEL = 'Users_app.User'

# Telling django to use modelbackend to allowe user login using username or email
AUTHENTICATION_BACKENDS = [
    'Users_app.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'Users_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'attendance_app',
    

    'crispy_forms',
    'crispy_bootstrap5',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'attendance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attendance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = 'media/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'


STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


LOGIN_URL = 'Users_app:login'
LOGIN_REDIRECT_URL = 'attendance_app:lecturer_dashboard'  # lecturer goes here by default

LOGOUT_REDIRECT_URL = 'Users_app:login'



# settings.py

JAZZMIN_SETTINGS = {
    # Title of the window (Browser tab title)
    "site_title": "Admin Control Panel",
    
    # Title on the login screen (Max 19 characters)
    "site_header": "UDUS QR ATTENDANCE",
    
    # Title on the brand text (Top left on the main dashboard sidebar)
    "site_brand": "UDUS QR ATTENDANCE",
    
    # Welcome sign on the login interface
    "welcome_sign": "Welcome back! Please sign in to manage operations.",
    
    # Copyright text inside the global footer element
    "copyright": "UDUS QR",
    
    # The model that will populate the global top-search bar if defined
    "search_model": ["auth.User"],

    # User Menu links on the top right (e.g., links to your main frontend site)
    "usermenu_links": [
        {"name": "View Live Site", "url": "/", "new_window": True},
    ],
    
    # Whether to show the sidebar organizer tool toggle
    "show_sidebar": True,
    "navigation_expanded": True,


    # Append this inside the JAZZMIN_SETTINGS dictionary
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        # Custom example: If you have a 'blog' app with a 'Post' model
        # "blog.post": "fas fa-file-alt",
    },
    # Default icon for apps/models that don't have an explicit icon set
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}